package com.mikuwxc.autoreply.wclocalsocket;

public interface WxCmdType {
    public static final int AUTO_VERIFY = 2008;
    public static final int CLEAR_BLACK_FRIENDS = 2021;
    public static final int GET_ADD_FRIEND_RESULT = 2013;
    public static final int GET_LUCKY_MONEY = 2018;
    public static final int GET_ONE_CHATROOM = 2010;
    public static final int GET_ONE_CONTACT = 2009;
    public static final int GET_OSS_STS = 1022;
    public static final int GET_OTHER_FRIENDS_MOMENT = 2020;
    public static final int GET_PHONE_APP_DISPLAY = 1018;
    public static final int GET_PHONE_AUTHORITY = 1017;
    public static final int GET_TRANS = 2019;
    public static final int INNER_DOWNLOAD_FILE = 9001;
    public static final int INNER_HANDLE_HEART = 9000;
    public static final int INNER_HANDLE_MOMENT_SUCCESS = 9002;
    public static final int INNER_SELECT_BATCH_MESSAGE = 9003;
    public static final int REPORT_ADD_FRIEND_RESULT = 1019;
    public static final int REPORT_BATCH_MESSAGE_RESULT = 1026;
    public static final int REPORT_CLEAR_BLACK_FRIEND_RESULT = 1025;
    public static final int REPORT_COLLECT_OTHER_MOMENT_RESULT = 1024;
    public static final int REPORT_CONNECT_REMOTE = 1002;
    public static final int REPORT_DEVICE_STATUS = 1023;
    public static final int REPORT_FRIEND_REQUEST = 1012;
    public static final int REPORT_INVOKE_MESSAGE = 1027;
    public static final int REPORT_MESSAGE = 1007;
    public static final int REPORT_MESSAGE_SEND_RESULT = 1009;
    public static final int REPORT_MOMENT_LIKE_RESULT = 1021;
    public static final int REPORT_MOMENT_SEND_RESULT = 1020;
    public static final int REPORT_NEW_FRIEND_REQUEST = 1008;
    public static final int REPORT_ONE_CHATROOM = 1011;
    public static final int REPORT_ONE_CONTACT = 1010;
    public static final int REPORT_PHONE_CALL_RESULT = 1016;
    public static final int REPORT_PHONE_SMS_RESULT = 1015;
    public static final int REPORT_RISK_OPERATE = 1014;
    public static final int REPORT_SYNC_CHAT_ROOM = 1005;
    public static final int REPORT_SYNC_CONTACTS = 1004;
    public static final int REPORT_SYNC_LABEL = 1006;
    public static final int REPORT_SYNC_SELF = 1003;
    public static final int REPORT_VERIFY_FRIEND = 2017;
    public static final int REPORT_VERIFY_FRIEND_CALLBACK = 1028;
    public static final int REPORT_WECHAT_STATUS = 1013;
    public static final int REVIOKE_MESSAGE = 2022;
    public static final int SEND_MESSAGE = 2002;
    public static final int UPDATE_CONTACT_LABEL = 2007;
    public static final int UPDATE_CONTACT_REMARK = 2003;
}